# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = rofi -show combi -modes combi -combi-modes "drun,symbolpicker,window,power,search" -combi-display-format "{text}" -show-icons -sort
$browser = firefox
$colorpicker = ~/.config/hypr/colorpicker.sh
$powermenu = rofi -show power -modes power -show-icons