# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = qs ipc call launcher open
$browser = firefox
$colorpicker = ~/.config/hypr/colorpicker.sh
$powermenu = rofi -show power -modes power -show-icons
