# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
    float_switch_override_focus = false

    touchpad {
        natural_scroll = false
        disable_while_typing = false
        scroll_factor = 0.3
        clickfinger_behavior = 1
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = elan07c9:00-04f3:3298-touchpad
    sensitivity = 0.3
    accel_profile = linear
}