# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = blueman-dock
    
    match:class = blueman-manager
    match:tag = waybar
    
    float = on
    pin = on
    size = 528 603
    move = monitor_w-528-10 monitor_h-603-32-10
    animation = slide bottom
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Enable tearing
windowrule {
    name = tearing
    match:fullscreen = true
    #match:content = 3
    
    immediate = on
}

# Make rofi instant
layerrule = no_anim on, match:namespace rofi

# Tray special workspace
workspace = special:tray, layout:scrolling, layoutopt:direction:down

windowrule {
    name = float_thunar_rename_popup
    match:initial_class = (Thunar|thunar)
    match:initial_title = ^Rename ".*"$

    float = on
    stay_focused = on
}

windowrule {
    name = mark_maximized_windows
    match:fullscreen_state_client = 1
    
    border_color = rgb(ffff77)
}
