# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Adwaita Mono

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    bezier = ease, 0.42, 0, 0.58, 1
    bezier = easeout, 0, 0, 0.58, 1
    bezier = easein, 0.42, 0, 1, 1
    animation = fadeIn, 1, 3, easeout
    animation = fadeOut, 1, 3, easeout
    animation = inputFieldDots, 1, 0.8, linear
}

background {
    monitor =
    path = screenshot
    color = rgba(0, 0, 0, 0.7)
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(00000011)

    outer_color = rgb(ffffff)
    check_color = rgb(aaaaaa)
    fail_color = rgb(ff3333)

    font_color = rgb(ffffff)
    fade_on_empty = false
    rounding = 5

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -2.5%
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = 0, 65
    halign = center
    valign = center
}

# DATE
# label {
#     monitor =
#     text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
#     font_size = 25
#     font_family = $font

#     position = 0, 150
#     halign = center
#     valign = bottom
# }

# USER
label {
    monitor =
    text = 󰀄 $USER
    font_size = 25
    font_family = $font

    position = 19.5, 12.5
    halign = left
    valign = bottom
}

# UPTIME
# label {
#     monitor =
#     text = cmd[update:60000] bash -c -- IFS=" " read -ra parts <<< $(uptime -r) && echo "${parts[2]}" # FIXME: Doesn't display and in kitty/zsh doesnt update while uptime -r on its own does, probably some cache BS
#     font_size = 25
#     font_family = $font

#     position = 19.5, 37.5
#     halign = left
#     valign = bottom
# }

# KEYBOARD LAYOUT
# label {
#     monitor =
#     text = $LAYOUT[en,ru]
#     font_size = 24
#     onclick = hyprctl switchxkblayout all next

#     position = 250, -20
#     halign = center
#     valign = center
# }