general {
    #lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    #before_sleep_cmd = loginctl lock-session    # lock before suspend.
    #after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    before_sleep_cmd = pidof hyprlock || hyprlock --no-fade-in
    after_sleep_cmd = hyprctl dispatch focuswindow class:hyprlock
}


listener {
    timeout = 240
    on-timeout = AC_ONLINE="$(cat /sys/class/power_supply/ACAD/online)"; if [ $AC_ONLINE == "0" ]; then brightnessctl -s set 0; fi
    on-resume = brightnessctl -r
}

listener {
    timeout = 300
    on-timeout = brightnessctl -r; AC_ONLINE="$(cat /sys/class/power_supply/ACAD/online)"; if [ $AC_ONLINE == "1" ]; then hyprlock; else systemctl sleep; fi
}
