# This is the main Hyprland config file.
# For the possible settings refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# This configuration is split into multiple files
# You should not edit settings in this file directly, instead edit those found in ~/.config/hypr/land/
# Hyprland does not automatically reload if one of these split files is saved. Either save this file or manually reload with hyprctl reload

source = ./land/monitors.conf
source = ./land/apps.conf
source = ./land/autostart.conf
source = ./land/env.conf
source = ./land/permissions.conf
source = ./land/appearance.conf
source = ./land/rules.conf
source = ./land/input.conf
source = ./land/binds.conf
source = ./land/misc.conf
source = ./land/layout.conf
source = ./land/render.conf