[mgr]
sort_by = "natural"
linemode = "size"
show_hidden = true # By default

[opener]
set-wallpaper = [
	{run = "qs ipc call wallpaper setWallpaper '%s1'", desc = "Set as wallpaper", for = "linux"},
]
run = [
	{run = "'%s1'", desc = "Run"},
]
run-java = [
	{run = "java -j '%s1'", desc = "Run with system Java"}, # TODO: Fix?
]
extract-zip = [
	{run = "unzip %s1 -d \"$(basename --suffix='.zip' -- %s1)\"", desc = "Extract here", for = "linux"},
]
edit = [ # Overwrite default
	{run = "rootDir=$(git rev-parse --show-toplevel) && cd $rootDir && unset rootDir; ${EDITOR:-vi} %s", desc = "$EDITOR", for = "unix", block = true},
]

[[open.prepend_rules]]
mime = "image/*"
use = ["open", "exif", "set-wallpaper"]
[[open.prepend_rules]]
mime = "application/{pie-,}executable"
use = ["run"]
[[open.prepend_rules]]
mime = "application/java-archive"
use = ["run-java"]
[[open.prepend_rules]]
mime = "application/{g,}zip"
use = ["extract-zip"]

[plugin]
previewers = [
	{mime = "vfs/absent", run = "faster-piper -- echo \"File not downloaded, can't preview\" | fold -s -w $w"},

	{url = "*/", run = "folder", sync = true},

	{mime = "text/*", run = "code"},
	{mime = "application/{x-nd,}json", run = "json"},
	{mime = "image/{avif,heic,svg+xml}", run = "magick --bg=none"}, # Needs conversion # FIXME: transparency
	{mime = "image/*", run = "image"},
	{mime = "audio/flac", run = "faster-piper -- file -b \"$1\" | fold -s -w $w; echo; echo 'Tags:'; metaflac --show-all-tags \"$1\" | sed 's/^/  /'"},
	{mime = "audio/mpeg", run = "faster-piper -- file -b \"$1\" | fold -s -w $w; echo; echo 'Tags:'; mid3v2 -l \"$1\" | tail -n +2 | sed 's/^/  /'"},
	{mime = "video/*", run = "video"},
	{mime = "application/pdf", run = "pdf"},
	{mime = "application/{g,}zip", run = "faster-piper --format=url -- zipinfo -1 \"$1\""},
	{mime = "application/{{g,}zip,x-{tar,bzip*,7z-compressed,xz,rar,iso9660-image}}", run = "archive"},
	{mime = "{font/*,application/{vnd.,}ms-opentype}", run = "font"},
	{url = "*.ttf", mime = "application/octet-stream", run = "font"},

	{url = "*", run = "file"}, # Fallback
]

prepend_spotters = [
	{mime = "audio/*", run = "audio"},
]

prepend_fetchers = [
	{url = "local://*",  run = "mime-ext.local",  prio = "high", group = "mime"},
	{url = "remote://*", run = "mime-ext.remote", prio = "high", group = "mime"},
]